

name: rawae_gp24
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter



  
  google_fonts: ^6.2.1
  delightful_toast: ^1.1.0
  get_it: ^8.0.0
  
  
  

  #fire base dependencies
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  firebase_auth: ^5.3.1 
  cloud_firestore: ^5.4.4 
  firebase_app_check: ^0.3.1+4
  firebase_database: ^11.1.4
  image_picker: ^1.1.2
  firebase_messaging: 15.1.3
  http: ^1.2.2
  cached_network_image: ^3.4.1
  googleapis_auth: ^1.0.0
  fast_rsa: ^3.6.6
  flutter_local_notifications: 17.2.1 

  dcdg: ^4.1.0 # this to generate the class diagram
  socket_io_client: ^2.0.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf


flutter:
  uses-material-design: true


  assets:
    - assets/book.png
    - assets/book2.png
    - assets/book3.png
    - assets/fantasy.png
    - assets/drama.png
    - assets/romance.png
    - assets/comedy.png
    - assets/crime_fiction.png
    - assets/adventure.png
    - assets/h.png
    - assets/default.png
    - assets/hunter.png
    - assets/cat.png
    - assets/catm.png
    - assets/profile2.png
    - assets/horror.png
    - assets/Thriller.png
    - assets/Mystery.png
    - assets/Historical.png
    - assets/Science Fiction.png



 




